### PR TITLE
Add: awesome-japanese-a11y-companies

### PR DESCRIPTION
**Pull request by yamanoku**
I have created an awesome-list of technology companies in Japan that are working on or promoting accessibility.

https://github.com/yamanoku/awesome-japanese-a11y-companies

### CODE REVIEW

**Review by brunopulis — CHANGES_REQUESTED** [review]
Thanks for your contributing @yamanoku :) I was thinking these companies make more sense on category "Companies and Organizations". 

What do you think?

**Comment by yamanoku** [comment]
@brunopulis I moved it! Please review it 😄

**Review by brunopulis — CHANGES_REQUESTED** [review]
Hi @yamanoku it would be interesting to remove the hyphen between the words and put the first letter capitalized. What do you think?

**Comment by yamanoku** [comment]
@brunopulis I fixed it!

**Review by brunopulis — APPROVED** [review]
Hey @yamanoku LGTM 🚀

**Pull request merged**
