### PR TITLE
add resources to tools list

### PR DESCRIPTION
**Pull request by olitreadwell**
Add NPM packages: 
- accessibility-checker
- cypress-accessibility-checker

add web extensions
- Chrome browser extension : IBM equal access accessibility checker
- Firefox browser add-on: IBM equal access accessibility checker

### CODE REVIEW

**Comment by olitreadwell** [comment]
@brunopulis I know it lists you as busy, is there someone else who might be able to review this? Hopefully these are helpful additions. Thanks for your time.

**Comment by brunopulis** [comment]
> @brunopulis I know it lists you as busy, is there someone else who might be able to review this? Hopefully these are helpful additions. Thanks for your time.

Sorry for delay I'll include on Awesome. Thanks for contributing 😉

**Review by brunopulis — APPROVED** [review]
LGTM

**Comment by olitreadwell** [comment]
Thanks @brunopulis !

**Pull request merged**
