### PR TITLE
add OSK software

### PR DESCRIPTION
**Pull request by onlurking**
This PR changes:

- change "Screen Readers" to "Assistive Technology" in README to be more broad for softwares regarding accessibility
- add a section with OSK (on-screen keyboard) technologies in `topics/assistive-technology.md`

### CODE REVIEW

**Comment by onlurking** [comment]
Related to #66

**Comment by brunopulis** [comment]
Thanks

**Comment by onlurking** [comment]
Hi @brunopulis, you closed the PR without merging, it was intended?

**Comment by brunopulis** [comment]
@onlurking sorry about that, I was traveling and my network was not so good. I reopen your PR thanks to contribute! :)

**Pull request merged**
