### PR TITLE
adding open soruce accessibility resources

### PR DESCRIPTION
**Pull request by mgifford**

### CODE REVIEW

**Review by brunopulis — CHANGES_REQUESTED** [review]
Hey @mgifford thanks for your contribution! What do you think we put the item in alphabetical order?

**Comment by mgifford** [comment]
@brunopulis that is just as good an idea as spelling open source correctly! Let me go adjust that PR.

**Comment by brunopulis** [comment]
@mgifford excellent! I was looking at your repository about accessibility courses and I thought it was fantastic, could we include these references in Awesome A11y?

**Review by brunopulis — APPROVED** [review]
LGTM

**Comment by mgifford** [comment]
Oh ya, and no problem using those resources. These ones? https://github.com/accessibility/a11y-courses

**Comment by brunopulis** [comment]
> Oh ya, and no problem using those resources. These ones? https://github.com/accessibility/a11y-courses

Yup, these ones! :)

**Comment by mgifford** [comment]
Yes, please do. And if there are things I've missed, please do a PR.  It's hard to keep up. I want to share these resources in the open so that they can be useful to others.

**Pull request merged**
