### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vanessametonini**
Added @marcysutton in "Who to follow" section. Removed https in twitter links (it can block people to access if you are not authenticated)

### CODE REVIEW

**Comment by brunopulis** [comment]
@vanessametonini :smile:  Thanks!

**Comment by marcysutton** [comment]
Thank you!

**Comment by brunopulis** [comment]
@marcysutton :D

**Comment by vanessametonini** [comment]
:D you are welcome @marcysutton

**Pull request merged**
